### ISSUE TITLE
Known warnings and issues

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/guide-microprofile-graphql#9]
There are some issues with the guide application that are known issues with GraphQL. They are listed here:

- [x] Warning message `Could not load service class com.ibm.ws.io.smallrye.graphql.component.GraphQLExtension`
  - https://github.com/OpenLiberty/open-liberty/issues/14188
- [x] GraphQL fails after updates in dev mode
  - https://github.com/OpenLiberty/open-liberty/issues/12641
- [x] Get following errors with tests:
```
java.lang.ExceptionInInitializerError
	at io.openliberty.guides.graphql.SystemIT.testGetSystem(SystemIT.java:55)
Caused by: java.lang.IllegalStateException: No ConfigProviderResolver implementation found!
	at io.openliberty.guides.graphql.SystemIT.testGetSystem(SystemIT.java:55)

java.lang.NoClassDefFoundError: Could not initialize class io.smallrye.graphql.client.typesafe.impl.HeaderBuilder
	at io.openliberty.guides.graphql.SystemIT.testEditNote(SystemIT.java:67)
```
  - Errors only appear when using version 1.0.14 of SmallRye GraphQL client dependencies
  - Errors do not occur when using version 1.0.3 or lower
  

List will be updated as others are encountered.

**Comment by AustinSeto** [comment]
Both of the following addressed

- GraphQL fails after updates in dev mode
- Get following errors with tests

Currently drafting guide without the use of dev mode, and testing with simple HTTP requests.

**Comment by AustinSeto** [comment]
Noticed when running changes in https://github.com/OpenLiberty/draft-guide-graphql-intro/pull/26 the `Could not load service class com.ibm.ws.io.smallrye.graphql.component.GraphQLExtension` warning no longer appears.
